# Generated by Django 6.0.5 on 2026-05-06 10:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('results', '0001_initial'),
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('term', 'Term Report'), ('yearly', 'Yearly Report'), ('transcript', 'Transcript')], max_length=20)),
                ('pdf_file', models.FileField(upload_to='reports/%Y/%m/')),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('download_count', models.IntegerField(default=0)),
                ('generated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='schools.schooluser')),
                ('term_summary', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='results.termsummary')),
                ('yearly_result', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='results.yearlyresult')),
            ],
        ),
        migrations.CreateModel(
            name='ReportCardTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_default', models.BooleanField(default=False)),
                ('show_logo', models.BooleanField(default=True)),
                ('show_school_name', models.BooleanField(default=True)),
                ('show_motto', models.BooleanField(default=True)),
                ('show_address', models.BooleanField(default=True)),
                ('show_attendance', models.BooleanField(default=True)),
                ('show_class_position', models.BooleanField(default=True)),
                ('show_teacher_comments', models.BooleanField(default=True)),
                ('show_headmaster_comment', models.BooleanField(default=True)),
                ('headmaster_signature', models.ImageField(blank=True, null=True, upload_to='signatures/')),
                ('headmaster_name', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_templates', to='schools.school')),
            ],
        ),
    ]
