# Generated by Django 6.0.5 on 2026-05-06 10:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('subdomain', models.CharField(db_index=True, max_length=50, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('address', models.TextField(blank=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='school_logos/')),
                ('theme_color', models.CharField(default='#4F46E5', help_text='Hex color code', max_length=7)),
                ('motto', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('pending', 'Pending Approval'), ('active', 'Active'), ('suspended', 'Suspended'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('is_demo', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('parent_registration_enabled', models.BooleanField(default=True)),
                ('registration_token', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('subscription_active', models.BooleanField(default=False)),
                ('subscription_expires', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GalleryItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video')], default='image', max_length=10)),
                ('image', models.ImageField(blank=True, help_text='Upload if media type is Image', null=True, upload_to='gallery/images/')),
                ('video_url', models.URLField(blank=True, help_text='YouTube or Vimeo URL if media type is Video', null=True)),
                ('is_featured', models.BooleanField(default=False, help_text='Show on the home page')),
                ('school', models.ForeignKey(blank=True, help_text='Leave blank for global showcase', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gallery_items', to='schools.school')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SchoolUser',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('role', models.CharField(choices=[('headmaster', 'Headmaster'), ('admin', 'School Admin'), ('teacher', 'Teacher'), ('student', 'Student'), ('parent', 'Parent')], db_index=True, max_length=20)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('signature', models.ImageField(blank=True, null=True, upload_to='signatures/')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='schools.school')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='school_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'school')},
            },
        ),
    ]
