# Generated by Django 6.0.4 on 2026-04-20 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='custom_css',
            field=models.TextField(blank=True, help_text='Custom CSS'),
        ),
        migrations.AddField(
            model_name='school',
            name='nav_order',
            field=models.JSONField(blank=True, default=dict, help_text='Nav reorder JSON'),
        ),
        migrations.AddField(
            model_name='school',
            name='sidebar_width',
            field=models.PositiveIntegerField(default=256, help_text='Sidebar width in px'),
        ),
    ]
