# Generated by Django 6.0.5 on 2026-05-15 21:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='ca_weight',
            field=models.FloatField(default=30.0, help_text='Weight percentage for Continuous Assessment (CA)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='school',
            name='exam_weight',
            field=models.FloatField(default=70.0, help_text='Weight percentage for Exam', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
