# Generated by Django 6.0.5 on 2026-05-15 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0002_school_ca_weight_school_exam_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='grading_system',
            field=models.CharField(choices=[('system', 'System Grading (Default: 30% CA, 70% Exam)'), ('custom_weights', 'Custom CA/Exam Weights'), ('multiple_components', 'Multiple Assessment Components'), ('subject_specific', 'Subject-Specific Grading')], default='system', help_text='Choose the grading system for your school', max_length=30),
        ),
    ]
