# Generated by Django 6.0.4 on 2026-04-28 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0003_remove_school_custom_css_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schooluser',
            name='signature',
            field=models.ImageField(blank=True, null=True, upload_to='signatures/'),
        ),
    ]
