# Generated by Django 6.0.4 on 2026-05-02 19:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0004_schooluser_signature'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video')], default='image', max_length=10)),
                ('image', models.ImageField(blank=True, help_text='Upload if media type is Image', null=True, upload_to='gallery/images/')),
                ('video_url', models.URLField(blank=True, help_text='YouTube or Vimeo URL if media type is Video', null=True)),
                ('is_featured', models.BooleanField(default=False, help_text='Show on the home page')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_items', to='schools.school')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
