# Generated by Django 6.0.4 on 2026-05-03 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0005_galleryitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='subdomain',
            field=models.CharField(db_index=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='schooluser',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='schooluser',
            name='role',
            field=models.CharField(choices=[('headmaster', 'Headmaster'), ('admin', 'School Admin'), ('teacher', 'Teacher'), ('student', 'Student'), ('parent', 'Parent')], db_index=True, max_length=20),
        ),
    ]
