# Generated by Django 6.0.4 on 2026-05-03 19:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0006_alter_school_subdomain_alter_schooluser_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galleryitem',
            name='school',
            field=models.ForeignKey(blank=True, help_text='Leave blank for global showcase', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gallery_items', to='schools.school'),
        ),
    ]
