# Generated by Django 6.0.4 on 2026-04-23 00:00

import django.db.models.deletion
from django.db import migrations, models


def backfill_parent_student_links(apps, schema_editor):
    Student = apps.get_model('academics', 'Student')
    ParentStudentLink = apps.get_model('academics', 'ParentStudentLink')
    SchoolUser = apps.get_model('schools', 'SchoolUser')

    parents = SchoolUser.objects.filter(role='parent')
    for parent in parents.iterator():
        user = getattr(parent, 'user', None)
        email = getattr(user, 'email', None)
        if not email:
            continue

        students = Student.objects.filter(
            school=parent.school,
            parent_email__iexact=email,
        )
        for student in students.iterator():
            ParentStudentLink.objects.get_or_create(
                school=parent.school,
                parent=parent,
                student=student,
                defaults={'relationship': 'parent'},
            )


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0002_school_custom_css_school_nav_order_and_more'),
        ('academics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParentStudentLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship', models.CharField(choices=[('parent', 'Parent'), ('guardian', 'Guardian')], default='parent', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(limit_choices_to={'role': 'parent'}, on_delete=django.db.models.deletion.CASCADE, related_name='child_links', to='schools.schooluser')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_student_links', to='schools.school')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_links', to='academics.student')),
            ],
            options={
                'ordering': ['student__admission_number'],
                'unique_together': {('parent', 'student')},
            },
        ),
        migrations.RunPython(backfill_parent_student_links, noop_reverse),
    ]
