# Generated by Django 6.0.4 on 2026-05-02 19:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_parentstudentlink'),
        ('schools', '0005_galleryitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachersubjectassignment',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_subject_assignments', to='schools.school'),
        ),
        migrations.AlterField(
            model_name='parentstudentlink',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent_student_links', to='schools.school'),
        ),
        migrations.AlterField(
            model_name='teachersubjectassignment',
            name='teacher',
            field=models.ForeignKey(limit_choices_to={'role': 'teacher'}, on_delete=django.db.models.deletion.CASCADE, related_name='subject_assignments', to='schools.schooluser'),
        ),
    ]
