# Generated by Django 6.0.4 on 2026-05-03 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_teachersubjectassignment_school_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='admission_number',
            field=models.CharField(db_index=True, max_length=50, unique=True),
        ),
    ]
